name: zabefest
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dio: ^5.3.2
  image_picker: ^1.0.4
  flutter_secure_storage: ^8.0.0
  # flutter_local_notifications: ^16.0.0  # Temporarily disabled for APK build
  shared_preferences: ^2.2.1
  logger: ^2.0.2
  intl: ^0.18.1
  animate_do: ^3.1.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    